# File: .github/workflows/repo-sync.yml
# From: https://github.com/repo-sync/github-sync

# .github/workflows/git-sync.yml

on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:jakdept/jakdept"
          source_branch: "main"
          destination_repo: "git@github.com:jakdept/jakdept.github.io"
          destination_branch: "main"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
